jake/Jake-robot/src/main/java/frc/robot/subsystems/Drivetrain.java

Created drivetrain

---

kaitlyn/kaitlyn-robot/src/main/java/frc/robot/subsystems/Drivetrain.java
kaitlyn/kaitlyn-robot/vendordeps/Phoenix.json

Added motors and basic methods

Added motors to drivetrain (Kaitlyn)

---

reese/Reese-Robot/src/main/java/frc/robot/subsystems/Drivetrain.java
reese/Reese-Robot/vendordeps/Phoenix.json

added motors

---

jake/Jake-robot/src/main/java/frc/robot/subsystems/Drivetrain.java
jake/Jake-robot/vendordeps/Phoenix.json

added drive train

---

reese/Reese-Robot/src/main/java/frc/robot/subsystems/Drivetrain.java

cleaned up and added comments

---

kaitlyn/kaitlyn-robot/src/main/java/frc/robot/subsystems/Drivetrain.java

Cleaned up (Kaitlyn)

---

kaitlyn/kaitlyn-robot/src/main/java/frc/robot/Robot.java
kaitlyn/kaitlyn-robot/src/main/java/frc/robot/RobotContainer.java
kaitlyn/kaitlyn-robot/src/main/java/frc/robot/commands/ArcadeDrive.java
kaitlyn/kaitlyn-robot/src/main/java/frc/robot/subsystems/Drivetrain.java

Finished ArcadeDrive and added Teleop commands to Robot.java and RobotContainer.java

Finished ArcadeDrive (Kaitlyn)

---

kaitlyn/kaitlyn-robot/src/main/java/frc/robot/Robot.java
kaitlyn/kaitlyn-robot/src/main/java/frc/robot/RobotContainer.java
kaitlyn/kaitlyn-robot/src/main/java/frc/robot/commands/ArcadeDrive.java

Edited Robot.java, connected Joystick to controller

Added Teleop Stuff (Kaitlyn)

---

jake/Jake-robot/src/main/java/frc/robot/commands/ArcadeDrive.java

Changed Teleop

---

jake/Jake-robot/src/main/java/frc/robot/Robot.java
jake/Jake-robot/src/main/java/frc/robot/RobotContainer.java
jake/Jake-robot/src/main/java/frc/robot/commands/ArcadeDrive.java
jake/Jake-robot/src/main/java/frc/robot/subsystems/intake/Hopper.java
jake/Jake-robot/src/main/java/frc/robot/subsystems/intake/IntakeArm.java

i pretty much wanted to save my code

I thought i already typed this into github

---

kaitlyn/kaitlyn-robot/src/main/java/frc/robot/Robot.java
kaitlyn/kaitlyn-robot/src/main/java/frc/robot/commands/ArcadeDrive.java
kaitlyn/kaitlyn-robot/src/main/java/frc/robot/subsystems/intake/Hopper.java
kaitlyn/kaitlyn-robot/src/main/java/frc/robot/subsystems/intake/IntakeArm.java

Edited Arcade Drive so that Smart Dashboard shows left and right

Added SmartDashboard stuff (Kaitlyn)

---

jake/Jake-robot/src/main/java/frc/robot/subsystems/intake/Hopper.java
jake/Jake-robot/src/main/java/frc/robot/subsystems/intake/IntakeArm.java
jake/Jake-robot/vendordeps/REVLib.json

We did Hopper Intake arm today

Hopper and Intake arm

---

kaitlyn/kaitlyn-robot/src/main/java/frc/robot/subsystems/intake/Hopper.java
kaitlyn/kaitlyn-robot/src/main/java/frc/robot/subsystems/intake/IntakeArm.java
kaitlyn/kaitlyn-robot/vendordeps/REVLib.json

Finished the subsystems Hopper and Intake Arm

Finished subsystem Hopper & Intake Arm (Kaitlyn)

---

kaitlyn/kaitlyn-robot/src/main/java/frc/robot/RobotContainer.java
kaitlyn/kaitlyn-robot/src/main/java/frc/robot/commands/RunIntake.java
kaitlyn/kaitlyn-robot/src/main/java/frc/robot/subsystems/intake/IntakeArm.java

Created RunIntake commands and edited RobotContainer

Created  RunIntake (Kaitlyn)

---

kaitlyn/kaitlyn-robot/src/main/java/frc/robot/commands/shooting/Draw.java
kaitlyn/kaitlyn-robot/src/main/java/frc/robot/commands/shooting/Latch.java
kaitlyn/kaitlyn-robot/src/main/java/frc/robot/commands/shooting/Launch.java
kaitlyn/kaitlyn-robot/src/main/java/frc/robot/commands/shooting/Reload.java
kaitlyn/kaitlyn-robot/src/main/java/frc/robot/subsystems/Shooter.java

Completed the shooter subsystem and added the related shooter commands

Finished Shooter Commands and Subsystems (Kaitlyn)

---

jake/Jake-robot/src/main/java/frc/robot/commands/Shooting/Draw.java
jake/Jake-robot/src/main/java/frc/robot/commands/Shooting/Latch.java
jake/Jake-robot/src/main/java/frc/robot/commands/Shooting/Launch.java
jake/Jake-robot/src/main/java/frc/robot/commands/Shooting/Reload.java
jake/Jake-robot/src/main/java/frc/robot/subsystems/Shooter.java

Reload Latch Draw launch

---

kaitlyn/kaitlyn-robot/src/main/java/frc/robot/RobotContainer.java

Added shooter commands to robot container

Updated Robot Container (Kaitlyn)

---

jake/Jake-robot/src/main/java/frc/robot/RobotContainer.java
jake/Jake-robot/src/main/java/frc/robot/commands/Shooting/Draw.java
jake/Jake-robot/src/main/java/frc/robot/commands/Shooting/Latch.java
jake/Jake-robot/src/main/java/frc/robot/commands/Shooting/Launch.java
jake/Jake-robot/src/main/java/frc/robot/commands/Shooting/Reload.java
jake/Jake-robot/src/main/java/frc/robot/subsystems/Shooter.java

shooter latch launch reload v2

shooter latch launch reload v2

---

kaitlyn/kaitlyn-robot/src/main/java/frc/robot/RobotContainer.java
kaitlyn/kaitlyn-robot/src/main/java/frc/robot/commands/RunIntake.java
kaitlyn/kaitlyn-robot/src/main/java/frc/robot/commands/shooting/Reload.java
kaitlyn/kaitlyn-robot/src/main/java/frc/robot/subsystems/Climb.java
kaitlyn/kaitlyn-robot/src/main/java/frc/robot/subsystems/Shooter.java

Debugged when testing code on robot

Debugged code (Kaitlyn)

---

kaitlyn/kaitlyn-robot/src/main/java/frc/robot/RobotContainer.java
kaitlyn/kaitlyn-robot/src/main/java/frc/robot/commands/RunIntake.java
kaitlyn/kaitlyn-robot/src/main/java/frc/robot/subsystems/Climb.java
kaitlyn/kaitlyn-robot/src/main/java/frc/robot/subsystems/Drivetrain.java

Organized code, added comments and whitespace

Organized Code (Kaitlyn)

---

kaitlyn/kaitlyn-robot/src/main/java/frc/robot/RobotContainer.java
kaitlyn/kaitlyn-robot/src/main/java/frc/robot/commands/ArcadeDrive.java
kaitlyn/kaitlyn-robot/src/main/java/frc/robot/commands/MoveForDistance.java
kaitlyn/kaitlyn-robot/src/main/java/frc/robot/subsystems/Drivetrain.java

Edited Drivetrain and added MoveForDistance command

Added autonomous (Kaitlyn)

---

reese/Reese-Robot/src/main/java/frc/robot/RobotContainer.java
reese/Reese-Robot/src/main/java/frc/robot/commands/MoveForDistance.java

finshed movefordistance

---

kaitlyn/kaitlyn-robot/src/main/java/frc/robot/RobotContainer.java
kaitlyn/kaitlyn-robot/src/main/java/frc/robot/commands/MoveForDistance.java

Finished MoveForDistance command and edited in Robot Container

Completed MoveForDistance (Kaitlyn)

---

jake/Jake-robot/src/main/java/frc/robot/commands/MoveForTime.java

Move fro time

---

jake/Jake-robot/src/main/java/frc/robot/commands/MoveForDistance.java

CREATE MOVE FOR DISTANCE

---

jake/Jake-robot/src/main/java/frc/robot/RobotContainer.java
jake/Jake-robot/src/main/java/frc/robot/commands/ArcadeDrive.java
jake/Jake-robot/src/main/java/frc/robot/commands/MoveForDistance.java
jake/Jake-robot/src/main/java/frc/robot/commands/MoveForTime.java
jake/Jake-robot/src/main/java/frc/robot/commands/MoveWithPID.java
jake/Jake-robot/src/main/java/frc/robot/subsystems/Drivetrain.java

MoveWithPID

---

reese/Reese-Robot/src/main/java/frc/robot/RobotContainer.java
reese/Reese-Robot/src/main/java/frc/robot/commands/ArcadeDrive.java
reese/Reese-Robot/src/main/java/frc/robot/commands/MoveWithPID.java
reese/Reese-Robot/src/main/java/frc/robot/subsystems/Drivetrain.java

worked on PID
